### ISSUE TITLE
dssp is only returned for the first chain_id in a .cif model

### ISSUE THREAD

**Issue by tueboesen** [PDB-REDO/dssp#11]
I just reported this as an issue in biopython here: https://github.com/biopython/biopython/issues/3505 
but after looking closer at it, I think it might actually be an issue in dssp rather than biopython.

The issue is that when I run the dssp on the file: '2mys.cif', which contains 3 chain_ids 'A','B','C' then I only get the dssp results from the first chain_id, 'A',  but not for the other two chains, which I believe I should be getting.

The structure can be found here:
https://www.rcsb.org/structure/2MYS

**Comment by drlemmus** [comment]
The problem is that chains B and C only contain coordinates for the CA atoms. Therefore no secondary structure assignment is possible for those chains using the DSSP algorithm. So it's not a bug as such, but we will look at improving the verbose output to make clear why it doesn't run on these protein chains.
