### ISSUE TITLE
Large structures and extra columns in DSSP file

### ISSUE THREAD

**Issue by JNWolf** [PDB-REDO/dssp#21]
Hi,

mostly we refer to pre-computed DSSP files, e.g., via 
`rsync -avz --delete rsync://rsync.cmbi.umcn.nl/dssp-from-mmcif/ /path_to_dssp/`
from the [DSSP website](https://swift.cmbi.umcn.nl/gv/dssp/DSSP_5.html).

For a pipeline working with MD simulation data, we need to compute DSSP files on our own and are therefore using your software. Now we stumbled over two things:
1) The DSSP files we create with your software do not contain the extra columns introduced for large structures / mmCIF, such as CHAIN and AUTHCHAIN. Is it possible to get these extra colums? I have not found an option in the help.
2) Your software seems not to be able to create DSSP files for large structures. It worked well when annotating the mmCIF, but when run with the option to create a DSSP file, chains with IDs of more than two characters are ignored. Interestingly, it seems that your software uses the PDB-style chain IDs (A..ZZZZ) instead of the author-given chain IDs (arbitrary) for this, even though author-given chain IDs are written to the DSSP file in the end. That would mean that your software only can correctly process up to 24 chains (A..Z).

Hope to hear from you. I also want to quickly thank for your last answer regarding the standalone version. We are still trying to compile it due to some errors and the issue was then already closed, but your answer really helped us.

Best wishes
Niclas

**Comment by drlemmus** [comment]
Hi Niclas,

1. The extra columns were a bit of a hack which had some adverse effect to other setups. We prefer to stick to the original DSSP format and for large complexes annotate mmCIF files directly. We realise that, currently, the mmCIF files do not capture all the data that you might want, but we are happy to enrich the mmCIF files if you tell us which information you need specifically.
2. That is indeed because of the limitations to the DSSP format. Notwithstanding, as chains in PDB format are case sensitive and allow digits we can faithfully process up to 62 chains. If you find cases that should fit, but somehow don't, please let us know.

If you need more help compiling, you are free to make a new issue. We're happy to help.

**Comment by JNWolf** [comment]
Hi Robbie,

thank you for your detailed answer. It is great to get such a fast response.

1. Sad to hear. We adjusted our parser to work with the extra columns. Thanks for the clarification, though. I guess we need to parse annotated mmCIFs then. We just need the secondary structure classification, so that is already part of the annotated mmCIF.
2. I understand. I was testing a large structure mmCIF, 3j9m, and chose the dssp output format. The result contains as last chain '1'. This chain has PBD-style chain ID 'Z'. In total the results contains 24 chains. That is why I concluded that DSSP only correctly processes 24 chains. But I guess you are referring to non-large structures in legacy PDB format. I am sure, DSSP works for the up to 62 chains there.

Concluding, it seems like DSSP moves forward to the annotated mmCIF output and we need to follow. But I guess this is the overall trend as other software, such as SCOT, also uses annotated mmCIFs. 

Thank you very much for your response and also for offering help compiling. Currently, we are waiting for out IT administrator, but we will get back to you if we need help. I will close the issue since my questions are answered, but please feel free to comment or message me if you feel need to.

Best wishes
Niclas
