### ISSUE TITLE
missing file when compile

### ISSUE THREAD

**Issue by Heisenburger2020** [PDB-REDO/dssp#71]
Dear Sir/Madam,

Thank you for your contribution!

I have met this problem when I was compiling at this step:
 cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/.local

CMake Error at /mnt/vepfs/fs_users/zhaojiale/libcifpp/build/cifpp/cifppConfig.cmake:27 (include):
  include could not find requested file:

    /mnt/vepfs/fs_users/zhaojiale/libcifpp/build/cifpp/cifppTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:108 (find_package)

I did installed latest libcifpp and somehow this file was missing. Is this because I had wrong version of libcifpp?

Yours Sincerely,
Jiale

**Comment by mhekkel** [comment]
Dear Jiale,

Did you install the development branch of libcifpp? That might explain, I'm considering renaming the cifpp cmake config files to be more in line with other tools. So kebab-case instead of CamelCase.

Theoretically, this should not be a problem, but in case you have a project configured already for the old name scheme, cmake will complain about a missing file. What you can do in that case is remove the _build_ directory and configure the project (DSSP in your case) anew.

I hope this helps?

**Comment by Heisenburger2020** [comment]
Thank you very much for your reply!
I just found out that I did not install zlib, which result in a failure in installing libcifpp. But it was not reported.

After I installed zlib, I could compile dssp successfully~ : )
