### ISSUE TITLE
Error while loading dictionary mmcif_pdbx.dic

### ISSUE THREAD

**Issue by soumya-dutt** [PDB-REDO/dssp#77]
I followed the instructions on the github to build mkdssp. Now I am facing this particular error while running mkdssp.

Error while loading dictionary mmcif_pdbx.dic
 >> Dictionary not found or defined (mmcif_pdbx.dic)
 
please help

**Comment by mhekkel** [comment]
The problem is the simplified installation, not everything is installed correctly yet. You can do several things:

- install [mrc](https://github.com/mhekkel/mrc) first and reconfigure/rebuild dssp. Works only if you do not have macOS
- build and install [libcifpp](https://github.com/pdb-redo/libcifpp). This will install the dictionary files
- Download the file [mmcif_pdbx.dic](https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_pdbx_v50.dic) and place it in /var/cache/libcifpp

For more information see https://pdb-redo.github.io/libcifpp/resources.html

**Comment by soumya-dutt** [comment]
Thank you so much.
I installed libcifpp and that worked.
