### ISSUE TITLE
Allow for the use system version for libmcfp

### ISSUE THREAD

**Issue by reneeotten** [PDB-REDO/dssp#79]
We package `dssp` in MacPorts and have the dependencies packaged as well. With the current version it downloads and installs 
`libmcfp` as part of the installation process. One can use `-DNOT PDB_REDO_META` to avoid that part, but then it doesn't find the systems version that is already installed.

**Comment by mhekkel** [comment]
You are right, for a short period I thought this was a good idea, but in alphafill I already reverted this. I'll tackle dssp asap.

**Comment by mhekkel** [comment]
fixed

**Comment by reneeotten** [comment]
thanks, trying to build this results in messages like:
```fatal error: 'cif++/text.hpp' file not found```

that is a file that doesn't get installed by the `libcifpp` package

**Comment by mhekkel** [comment]
Yes, I have a fix for that ready but haven't tested it yet. Since you use an 'exotic' system you might want to try the develop branch of libcifpp and see if that installs correctly? I changed some code there to fix staging, but I'm not sure if that really works. Don't know how to test it, well, did not have the time to find out
